-- CreateEnum
CREATE TYPE "Role" AS ENUM ('STUDENT', 'TEACHER', 'PARENT', 'ADMIN');
CREATE TYPE "PathwayCode" AS ENUM ('STEM', 'SOCIAL_SCIENCES', 'ARTS_AND_SPORTS');
CREATE TYPE "SchoolType" AS ENUM ('PUBLIC', 'PRIVATE', 'INTERNATIONAL', 'TVET');
CREATE TYPE "ContentType" AS ENUM ('video', 'pdf', 'quiz', 'activity');
CREATE TYPE "AssessmentType" AS ENUM ('formative', 'summative', 'project');
CREATE TYPE "QuestionType" AS ENUM ('MCQ', 'structured', 'essay');
CREATE TYPE "CompetencyKey" AS ENUM ('COMMUNICATION_COLLABORATION', 'CRITICAL_THINKING_PROBLEM_SOLVING', 'CREATIVITY_IMAGINATION', 'CITIZENSHIP', 'DIGITAL_LITERACY', 'LEARNING_TO_LEARN', 'SELF_EFFICACY');
CREATE TYPE "NationalValue" AS ENUM ('UNITY', 'INTEGRITY', 'SUSTAINABILITY', 'RESPONSIBILITY', 'RESPECT', 'PATRIOTISM');

CREATE TABLE "School" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "county" TEXT NOT NULL, "type" "SchoolType" NOT NULL DEFAULT 'PUBLIC', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "School_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Pathway" ("id" TEXT NOT NULL, "code" "PathwayCode" NOT NULL, "name" TEXT NOT NULL, "description" TEXT NOT NULL, "careerOutcomes" TEXT[], "kuccpsCourses" TEXT[], "tvetOptions" TEXT[], CONSTRAINT "Pathway_pkey" PRIMARY KEY ("id"));
CREATE TABLE "User" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "role" "Role" NOT NULL, "pathway" "PathwayCode", "grade" INTEGER, "school_id" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ParentStudent" ("id" TEXT NOT NULL, "parentId" TEXT NOT NULL, "studentId" TEXT NOT NULL, CONSTRAINT "ParentStudent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Subject" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "pathway_id" TEXT NOT NULL, "grade_level" INTEGER NOT NULL, "syllabus_code" TEXT NOT NULL, "overview" TEXT NOT NULL, "resources" JSONB NOT NULL DEFAULT '[]', CONSTRAINT "Subject_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Unit" ("id" TEXT NOT NULL, "subject_id" TEXT NOT NULL, "title" TEXT NOT NULL, "sequence_number" INTEGER NOT NULL, "learning_outcomes" TEXT[], "projectBrief" TEXT NOT NULL, "rubric" JSONB NOT NULL DEFAULT '[]', "values" "NationalValue"[], "ppiLinks" TEXT[], CONSTRAINT "Unit_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Lesson" ("id" TEXT NOT NULL, "unit_id" TEXT NOT NULL, "title" TEXT NOT NULL, "content_type" "ContentType" NOT NULL, "content_url" TEXT NOT NULL, "duration_mins" INTEGER NOT NULL, "notesPrompt" TEXT NOT NULL, CONSTRAINT "Lesson_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Assessment" ("id" TEXT NOT NULL, "subject_id" TEXT NOT NULL, "title" TEXT NOT NULL, "type" "AssessmentType" NOT NULL, "total_marks" INTEGER NOT NULL, "due_date" TIMESTAMP(3) NOT NULL, "durationMins" INTEGER NOT NULL DEFAULT 45, CONSTRAINT "Assessment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Question" ("id" TEXT NOT NULL, "assessment_id" TEXT NOT NULL, "text" TEXT NOT NULL, "type" "QuestionType" NOT NULL, "marks" INTEGER NOT NULL, "correct_answer" TEXT, "options" TEXT[], "explanation" TEXT, CONSTRAINT "Question_pkey" PRIMARY KEY ("id"));
CREATE TABLE "StudentProgress" ("id" TEXT NOT NULL, "student_id" TEXT NOT NULL, "lesson_id" TEXT NOT NULL, "completed_at" TIMESTAMP(3), "score" DOUBLE PRECISION, "time_spent_mins" INTEGER NOT NULL DEFAULT 0, "personalNotes" TEXT, CONSTRAINT "StudentProgress_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Grade" ("id" TEXT NOT NULL, "student_id" TEXT NOT NULL, "assessment_id" TEXT NOT NULL, "marks_obtained" DOUBLE PRECISION NOT NULL, "teacher_remarks" TEXT, "graded_at" TIMESTAMP(3), "submission" JSONB NOT NULL DEFAULT '{}', "needsReview" BOOLEAN NOT NULL DEFAULT false, CONSTRAINT "Grade_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TeacherNote" ("id" TEXT NOT NULL, "teacher_id" TEXT NOT NULL, "subject_id" TEXT NOT NULL, "unit_id" TEXT, "file_url" TEXT NOT NULL, "title" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "TeacherNote_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Announcement" ("id" TEXT NOT NULL, "school_id" TEXT NOT NULL, "author_id" TEXT NOT NULL, "title" TEXT NOT NULL, "body" TEXT NOT NULL, "pathway" "PathwayCode", "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Announcement_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Message" ("id" TEXT NOT NULL, "sender_id" TEXT NOT NULL, "receiver_id" TEXT NOT NULL, "subject" TEXT NOT NULL, "body" TEXT NOT NULL, "read" BOOLEAN NOT NULL DEFAULT false, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Message_pkey" PRIMARY KEY ("id"));
CREATE TABLE "StudentCompetency" ("id" TEXT NOT NULL, "studentId" TEXT NOT NULL, "competency" "CompetencyKey" NOT NULL, "score" INTEGER NOT NULL DEFAULT 50, "evidence" TEXT, CONSTRAINT "StudentCompetency_pkey" PRIMARY KEY ("id"));
CREATE TABLE "_TeacherSubjects" ("A" TEXT NOT NULL, "B" TEXT NOT NULL);

CREATE UNIQUE INDEX "Pathway_code_key" ON "Pathway"("code");
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "ParentStudent_parentId_studentId_key" ON "ParentStudent"("parentId", "studentId");
CREATE UNIQUE INDEX "Subject_name_grade_level_key" ON "Subject"("name", "grade_level");
CREATE UNIQUE INDEX "Unit_subject_id_sequence_number_key" ON "Unit"("subject_id", "sequence_number");
CREATE UNIQUE INDEX "StudentProgress_student_id_lesson_id_key" ON "StudentProgress"("student_id", "lesson_id");
CREATE UNIQUE INDEX "Grade_student_id_assessment_id_key" ON "Grade"("student_id", "assessment_id");
CREATE UNIQUE INDEX "StudentCompetency_studentId_competency_key" ON "StudentCompetency"("studentId", "competency");
CREATE UNIQUE INDEX "_TeacherSubjects_AB_unique" ON "_TeacherSubjects"("A", "B");
CREATE INDEX "_TeacherSubjects_B_index" ON "_TeacherSubjects"("B");

ALTER TABLE "User" ADD CONSTRAINT "User_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "School"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ParentStudent" ADD CONSTRAINT "ParentStudent_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ParentStudent" ADD CONSTRAINT "ParentStudent_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Subject" ADD CONSTRAINT "Subject_pathway_id_fkey" FOREIGN KEY ("pathway_id") REFERENCES "Pathway"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Unit" ADD CONSTRAINT "Unit_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "Subject"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Lesson" ADD CONSTRAINT "Lesson_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "Unit"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Assessment" ADD CONSTRAINT "Assessment_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "Subject"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Question" ADD CONSTRAINT "Question_assessment_id_fkey" FOREIGN KEY ("assessment_id") REFERENCES "Assessment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StudentProgress" ADD CONSTRAINT "StudentProgress_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StudentProgress" ADD CONSTRAINT "StudentProgress_lesson_id_fkey" FOREIGN KEY ("lesson_id") REFERENCES "Lesson"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Grade" ADD CONSTRAINT "Grade_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Grade" ADD CONSTRAINT "Grade_assessment_id_fkey" FOREIGN KEY ("assessment_id") REFERENCES "Assessment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TeacherNote" ADD CONSTRAINT "TeacherNote_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TeacherNote" ADD CONSTRAINT "TeacherNote_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "Subject"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TeacherNote" ADD CONSTRAINT "TeacherNote_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "Unit"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Announcement" ADD CONSTRAINT "Announcement_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Announcement" ADD CONSTRAINT "Announcement_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Message" ADD CONSTRAINT "Message_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Message" ADD CONSTRAINT "Message_receiver_id_fkey" FOREIGN KEY ("receiver_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StudentCompetency" ADD CONSTRAINT "StudentCompetency_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "_TeacherSubjects" ADD CONSTRAINT "_TeacherSubjects_A_fkey" FOREIGN KEY ("A") REFERENCES "Subject"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "_TeacherSubjects" ADD CONSTRAINT "_TeacherSubjects_B_fkey" FOREIGN KEY ("B") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
